site_name: SJTUOJ解答集
site_url: https://oj.sjtucs.com
theme:
  name: 'material'
  custom_dir: overrides
  palette:
    primary: cyan
repo_url: https://github.com/SJTU-OJ/SJTU-OJ.github.io/
repo_name: SJTU-OJ/SJTU-OJ.github.io
site_description: 一个SJTUOJ的题解分享网站
google_analytics: ['UA-159960487-2', 'oj']
markdown_extensions:
    - admonition
    - codehilite
    - meta
plugins:
    - search
    - minify:
        minify_html: false
        minify_js: false
        htmlmin_opts:
            remove_comments: true
nav:
    - 主页: index.md
    - 索引: nr/index.md
    - 添加: add.md
    - 鸣谢: thanks.md
    - 关于: about.md
